### ISSUE TITLE
Label and button text

### ISSUE THREAD

**Issue by tbnv** [atwellpub/resend-welcome-email#16]
Hello,

The label and button text use the same text string.
Please could you change this? Semantically, it's weird. 🙂

Something like: `Welcome email` and `Send new`

Or at least provide a gettext context.
It would also allow better translation (at least in French).

**Comment by atwellpub** [comment]
Hi, sure that sounds okay to me. I'll add the recommended changes in 1.1.5.

**Comment by tbnv** [comment]
Awesome, thanks @atwellpub!
